import { Poppins } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import "./main.css";
import "./responsive.css";
import BootstrapClient from "@/bootstrap/BootstrapClient";
import Providers from "../utils/providers";
import { Toaster } from "react-hot-toast";
import { getUser } from "@/utils/getUser";
import AuthProvider from "@/components/auth/AuthProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Toaster />
        <Providers>
          <AuthProvider>
            <BootstrapClient />
            {children}
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
